"""add llm_provider to users

Revision ID: 9a3e78ceb219
Revises: fd9c5e297da2
Create Date: 2026-07-22 16:03:02.050438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3e78ceb219'
down_revision = 'fd9c5e297da2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('llm_provider', sa.String(length=20), nullable=False, server_default='openai'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'llm_provider')
    # ### end Alembic commands ###
